title: Wiki Template
description: A simple wiki template using Jekyll
baseurl: "/wiki-template"
url: "https://www.justneki.com"

markdown: kramdown
theme: minima

collections:
  wiki:
    output: true
    permalink: /wiki/:path/

defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"
  - scope:
      path: ""
    values:
      layout: "default"