title: Patch Notes
description: Your site description
baseurl: ""
url: ""

markdown: kramdown
theme: minima

collections:
  wiki:
    output: true
    permalink: /wiki/:path/

defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"